### PR TITLE
adds new test to eliminate false postive results

### LINKED ISSUE #5: Doesn't Check Yield Well Enough
https://github.com/danielglatstein/my-each-000

His implementation shows you can build my-each without actually yielding - we need to test different blocks to make sure they aren't implementing the test blocks logic in the method.

### LINKED ISSUE #8: RSpec passing false positives
As per README:

>Here's an example of what should happen when you call your my_each method:

>```Ruby
>collection = [1, 2, 3, 4]
>my_each(collection) do |i|
>  puts i
>end
>```
>This should output:
>```
>1
>2
>3
>4
>```
and return:

>`#=> [1, 2, 3, 4]`

>Just like the real .each method.

Two passing PRs in this lab's repo (commits [e7a640](https://github.com/Biletnikoff/my-each-001/commit/e7a640aa63710e2d3f901deea5bf656e5c034576) & [d9d9cd](https://github.com/ruthmesfun/my-each-001/commit/d9d9cd128aa16359ea34c78050b4b6a172b613c0)) contain variants of the following code:

```Ruby
def my_each(array) 
  while array.length > 0
    yield(array)
    array.pop
  end
  return array
end
```

which outputs:

```
1
2
3
4
1
2
3
1
2
1
=> []
```

The above code should not satisfy the parameters set forth in the README, and therefore seems to be an instance of RSpec passing a false positive.

In addition, the README instructs students to:

> ...try to write your own version of the .each method without using the `.each` method provided by Ruby.

yet a passing PR (commit [4155fb](https://github.com/AnthonyRNL/my-each-001/commit/4155fba54af724f9a649bd4eb852265f068ba15a)) utilizes `.each` within `my_each`. This seems like another instance of RSpec passing a false positive, and including another test to prevent this in the future may be an appropriate solution.

### PR DESCRIPTION
**Pull request by deniznida**
The new tests check if the students really used yield and if the original array is being returned.
@jmburges 
closes #8 and closes #5

### CODE REVIEW

**Comment by jmburges** [comment]
This looks good, except it doesn't actually resolve #8.  If you're code is this:

```
require 'pry'

def my_each(array) 
  saved = array.dup
  while array.length > 0
    yield(array)
    array.pop
  end
  return saved
end

binding.pry
```

and run the `my_each.rb` file and run `my_each([1,2,3]) {|a| puts a}` it prints out 

```
1
2
3
1
2
1
```

That's not correct, yet that solution passes the tests!

**Comment by deniznida** [comment]
@jmburges added new test to check if the original array was modified.

**Comment by jmburges** [comment]
Is that the real root problem of that code? For example, this also passes:

```ruby
require 'pry'

def my_each(array) 
  i = array.count 
  while i > 0
    yield(array)
    i -= 1
  end
  return array
end

binding.pry
```

yet when your run `my_each([1,2,3]) {|a| puts a}` you get 

```
1
2
3
1
2
3
1
2
3
```

That's still not what we want. You are testing for a bunch of side effects, but this test doesn't actually test the thing that this method does. This method is meant to take a block, and run whatever command is in the block for each element. So you need to test that the block is run `count` times and that only a single element is passed into that block.

**Comment by jmburges** [comment]
and that each of the elements passed in, are in the original array, and no elements that aren't in the array get passed in.

**Comment by jmburges** [comment]
(but a check on making sure the array isn't modified is an awesome test! makes your code way more defensive)

**Comment by deniznida** [comment]
@jmburges I added the 2 test you mentioned, please let me know if there are other edge cases you'd like tests for.

**Comment by jmburges** [comment]
Looks good! :shipit:

**Pull request merged**
